version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.3
    working_directory: ~/pf_app
    steps:
      - checkout:
          path: ~/pf_app
      - ruby/install-deps

  install_chrome:
    docker:
      - image: cimg/ruby:2.7.3
    steps:
      - run:
          name: Install Chrome
          command: |
            wget -q -O chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i chrome.deb
            sudo apt-get install -f -y
      - run:
          name: Install ChromeDriver
          command: |
            CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
            wget -q -O chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip -d /usr/local/bin
            rm chromedriver_linux64.zip

  rubocop:
    docker:
      - image: cimg/ruby:2.7.3
    working_directory: ~/pf_app
    steps:
      - checkout:
          path: ~/pf_app
      - ruby/install-deps
      - run:
          name: Run rubocop
          command: bundle exec rubocop

  rspec:
    docker:
      - image: cimg/ruby:2.7.3-node
      - image: cimg/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: myapp_test
          MYSQL_USER: test
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/pf_app
    steps:
      - checkout:
          path: ~/pf_app
      - ruby/install-deps
      - run:
          name: yarn Install
          command: yarn install
      - run:
          name: webpack install
          command: bundle exec bin/webpack
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: Run rspec
          command: bundle exec rails spec

workflows:
  version: 2.1
  build_test:
    jobs:
      - build
      - install_chrome:
          requires:
            - build
      - rubocop:
          requires:
            - build
      - rspec:
          requires:
            - build
