version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.3
    working_directory: ~/pf_app
    steps:
      - checkout:
          path: ~/pf_app
      - ruby/install-deps

  install_chrome:
    docker:
      - image: cimg/ruby:2.7.3
    steps:
      - run:
          name: Install Chrome
          command: |
            curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list
            apt-get update
            apt-get install -y google-chrome-stable

  rubocop:
    docker:
      - image: cimg/ruby:2.7.3
    working_directory: ~/pf_app
    steps:
      - checkout:
          path: ~/pf_app
      - ruby/install-deps
      - run:
          name: Run rubocop
          command: bundle exec rubocop

  rspec:
    docker:
      - image: cimg/ruby:2.7.3-node
      - image: cimg/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: myapp_test
          MYSQL_USER: test
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/pf_app
    steps:
      - checkout:
          path: ~/pf_app
      - run:
          name: yarn Install
          command: yarn install
      - run:
          name: webpack install
          command: bundle exec bin/webpack
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: Run rspec
          command: bundle exec rails spec

workflows:
  version: 2.1
  build_test:
    jobs:
      - build
      - install_chrome:
          requires:
            - build
      - rubocop:
          requires:
            - build
      - rspec:
          requires:
            - build
